name: Generate Metrics

permissions:
  contents: write 

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: yeashy
          filename: github-metrics.svg

          base: header, activity, community, repositories, metadata

          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_ignored: html, css, vue, makefile, hack
          plugin_languages_limit: 8
          plugin_languages_sections: most-used, recently-used
          plugin_languages_details: bytes-size, percentage, lines, commits
          plugin_languages_ignored_repos: Bilingo-frontend, unit-tests, alt-studio-front, alt-studio-back, Web-HITs-Frontend-1, Web-HITs-Frontend-2, Web-HITs-Frontend-3, Web-HITs-Frontend-4, BattleshipsGame

          plugin_stars: yes
          plugin_stars_limit: 5

          plugin_repositories: yes
          plugin_repositories_affiliations: owner
          plugin_repositories_pinned: 3

          plugin_activity: yes
          plugin_activity_limit: 6
          plugin_activity_load: 300
          plugin_activity_days: 14
          plugin_activity_filter: all

          plugin_followup: yes
          plugin_followup_sections: repositories, users

          plugin_lines: yes

          plugin_calendar: yes
          plugin_calendar_limit: 1

          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_types: commit, pull_request, issue
          plugin_notable_repositories: yes

          plugin_topics: yes
          plugin_topics_mode: icons
          plugin_topics_limit: 12

          plugin_habits: yes
          plugin_habits_facts: yes
          plugin_habits_charts: yes

          plugin_people: yes
          plugin_people_types: followers, following
          plugin_people_limit: 24
